# add key to root
---
- hosts: all
  become: true
  ignore_errors: true
  
  vars:
     ssh_key:

  tasks:
#***************add_ssh-key-to-root**********************
#********************************************************
  - name: put pubkey
    lineinfile:
      path: "~/.ssh/authorized_keys"
      line: "{{ ssh_key }}"
