# basic install
---
- hosts: all
  become: yes
  become_method: su
  become_user: jazz3
  ignore_errors: true
  vars:
    ssh_key:

  tasks:
#***************add_ssh-key-to-root**********************
#********************************************************
  - name: put pubkey
    lineinfile:
      path: "/root/.ssh/authorized_keys"
      line: "{{ ssh_key }}"
