# add key to root
---
- hosts: all
  become: true
  ignore_errors: true
  
  vars:
     ssh_key:
     ssh_key_02:

  tasks:
#***************add_ssh-key-to-root**********************
#********************************************************
  - name: put pubkey
    lineinfile:
      path: "~/.ssh/authorized_keys"
      line: "{{ ssh_key }}"
      
  - name: put pubkey ssh_key_02
    lineinfile:
      path: "~/.ssh/authorized_keys"
      line: "{{ ssh_key_02 }}"
