# basic install
---
- hosts: all
  become: true
  ignore_errors: true
  host_key_checking: false

  tasks:
#***************update & upgrade*************************
#********************************************************
  - name: update
    apt: upgrade=dist force_apt_get=yes

  - name: upgrade 
    apt: upgrade=dist force_apt_get=yes

#***************install soft & utils********************
#*******************************************************
  - name: Install packages
    apt:
      name:
      - mc
      - htop
      - net-tools
      - mlocate
      - git
      - lnav
      - ntp
      - tree
      - sshfs
      state: latest
      
#*****************~create ~/.nanorc~*********************
#********************************************************  
  - name: Creating an ~/.nanorc file
    file: 
      path: ~/.nanorc
      state: touch
      
#*****************~set line Numbers in nano~*************
#********************************************************      
  - name: enable line numbers in nano editor
    lineinfile: 
      path: ~/.nanorc
#      state: touch
      line: set linenumbers
       

#*****************set-up time-zone***********************
#********************************************************
  - name: chandge time-zone
    timezone:
      name: Europe/Kiev
