---
- hosts: all
  gather_facts: true
  become: true
  ignore_errors: true

  vars:
    target_host:
    ssh_key_filename: id_rsa
#    contents: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"

  tasks:
  - name: generate SSH key "{{ssh_key_filename}}"
    openssh_keypair:
      path: "/root/.ssh/{{ssh_key_filename}}"
      type: rsa
      size: 2048
      state: present
      force: no

  - name: Fetch the keyfile from the node to master
    shell: cat ~/.ssh/id_rsa.pub
    register: contents
      
  - name: Copy the key add to authorized_keys using Ansible module
    delegate_to: 192.168.168.13
    delegate_facts: true
    lineinfile:
     path: "~/.ssh/authorized_keys"
     line: "{{ contents }}"
