---
- hosts: all
  gather_facts: true
  become: true
  ignore_errors: true

  vars:
    target_host:
    ssh_key_filename: id_rsa
#    contents: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"

  tasks:
  - name: "Installing Rsync"
    apt: >
      pkg={{ item }}
      state=latest
      update_cache=yes
      cache_valid_time=3600
    with_items:
    - rsync
    
  - name: generate SSH key "{{ssh_key_filename}}"
    openssh_keypair:
      path: "/root/.ssh/{{ansible_hostname}}-{{ssh_key_filename}}"
      type: rsa
      size: 2048
      state: present
      force: no
      
  - name: Synchronization of src on delegate host to dest on the current inventory host.
    copy:
      src: ~/.ssh/id_rsa.pub
      dest: /remote-keys/{{ ansible_hostname }}.pub
#      remote_src: true  
    delegate_to: 192.168.168.13    
      
#  - name: "Copy the public Key using Lookup"
#    shell: 
#      cmd: 'cat ~/.ssh/id_rsa.pub'
#    register: key
    
    
#  - name: Copy the key add to authorized_keys using Ansible module
#    delegate_to: 192.168.168.13
#    delegate_facts: true
#    lineinfile:
#     path: "~/ssh-pub/1txt"
#     line: "{{ key }}"  
      
#  - name: Copy Remote-To-Remote (from nodes to sftp)
#   synchronize: 
#       src: ~/.ssh/id_rsa.pub
#       dest: /ssh-pub/
#    delegate_to: 192.168.168.13
# replaseautorization file      
#  - name: copy key line to sftp
#    ansible.builtin.copy:
#      remote_src: true
#      src: ~/.ssh/id_rsa.pub
#      dest: ~/.ssh/authorized_keys
#    delegate_to: 192.168.168.13

#  - name: copy key to sftp
#    ansible.builtin.copy:
#      src: ~/.ssh/id_rsa.pub
#      remote_src: true
#      dest: /remote-keys/{{ ansible_hostname }}.pub
#      mode: pull
#    delegate_to: 192.168.168.13
