---
- hosts: all
  gather_facts: true
  become: true
  ignore_errors: true

  vars:
    target_host:
    ssh_key_filename: id_rsa

  tasks:
  - name: "Installing Rsync"
    apt: >
      pkg={{ item }}
      state=latest
      update_cache=yes
      cache_valid_time=3600
    with_items:
    - rsync
    
  - name: generate SSH key "{{ssh_key_filename}}"
    openssh_keypair:
      path: "/root/.ssh/{{ansible_hostname}}"
      type: rsa
      size: 2048
      state: present
      force: no
  - name: "Copy the public Key using Lookup"
    shell: 
      cmd: 'cat ~/.ssh/id_rsa.pub'
    register: key
    
  - name: Copy the key add to authorized_keys using Ansible module
    delegate_to: "{{ srv_ip}}"
    delegate_facts: true
    lineinfile:
     path: "~/.ssh/authorized_keys"
     line: "{{ key.stdout }}{{ ansible_hostname }}"
