---
- hosts: all
  gather_facts: true
  become: true
  ignore_errors: true

  vars:
    target_host:

  tasks:
  - name: Generate /etc/ssh/ RSA host key
    command : ssh-keygen -q -t rsa -f /etc/ssh/ssh_host_rsa_key -C "" -N ""
    args:
      creates: ~/.ssh/ssh_host_rsa_key

  - name: Generate /etc/ssh/ DSA host key
    command : ssh-keygen -q -t dsa -f /etc/ssh/ssh_host_dsa_key -C "" -N ""
    args:
      creates: ~/.ssh//ssh_host_dsa_key

  - name: Generate /etc/ssh/ ECDSA host key
    command : ssh-keygen -q -t ecdsa -f /etc/ssh/ssh_host_ecdsa_key -C "" -N ""
    args:
      creates: ~/.ssh//ssh_host_ecdsa_key

  - name: Fetch the keyfile from the node to master
    tags: run
    fetch: 
      src: "~/.ssh/id_rsa.pub"
      dest: "buffer/{{ansible_hostname}}-id_rsa.pub"
      flat: yes
