---
- hosts: all
  gather_facts: true
  become: true
  ignore_errors: true

  vars:
    target_host:
    ssh_key_filename: id_rsa
#    contents: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"

  tasks:
  - name: generate SSH key "{{ssh_key_filename}}"
    openssh_keypair:
      path: "/root/.ssh/{{ssh_key_filename}}"
      type: rsa
      size: 2048
      state: present
      force: no
      
#  - name: Fetch the keyfile from the node to master
#    tags: run
#    fetch: 
#      src: "~/.ssh/id_rsa.pub"
#      dest: "buffer/{{ansible_hostname}}-id_rsa.pub"
#      flat: yes
#    register: key
#
#  - name: Copy the key add to authorized_keys using Ansible module
#    tags: runcd
#    delegate_to: 192.168.168.13
#    delegate_facts: true
#    authorized_key:
#      user: vagrant
#      state: present
#      key: "{{ lookup('file','buffer/{{item}}-id_rsa.pub')}}"
#    when: "{{ item != ansible_hostname }}"
#    with_items: 
#      - "{{ groups['all'] }}"       
#
#  - name: "Copy the public Key using Lookup"
#    shell: 
#      cmd: 'cat ~/.ssh/id_rsa.pub'
#    register: key
#
#  - set_fact:
#      key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
#  - debug:
#      msg: "{{ key }}"
#  - debug: msg="{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
#    register: key
  - name:
    command: cat ~/.ssh/id_rsa.pub
    register: key
 # - copy:
 #   content: "{{ ~/.ssh/id_rsa.pub }}"
 #   delegate_to: 192.168.168.13
 #   dest: "~/.ssh/authorized_keys"

  - name: Copy the key add to authorized_keys using Ansible module
    delegate_to: 192.168.168.13
#    delegate_facts: true
    lineinfile:
     path: "~/.ssh/authorized_keys"
     line: "{{ key }}"
