---
- hosts: all
  gather_facts: true
  become: true
  ignore_errors: true

  vars:
    target_host:
    ssh_key_filename: id_rsa

  tasks:
  - name: generate SSH key "{{ssh_key_filename}}"
    openssh_keypair:
      path: "/root/.ssh/{{ssh_key_filename}}"
      type: rsa
      size: 2048
      state: present
      force: no
      comment: {{ ansible_facts['nodename'] }}

  - name: Fetch the keyfile from the node to master
    tags: run
    fetch: 
      src: "~/.ssh/id_rsa.pub"
      dest: "buffer/{{ansible_hostname}}-id_rsa.pub"
      flat: yes
      register: result
      
  - debug:
    msg: result
