---
- hosts: all
  gather_facts: yes
  become: true
  ignore_errors: true

  tasks:
 #     - name: gather os specific variables
 #       include_vars: "{{ item }}"
 #       with_first_found:
 #           - "vars/{{ ansible_distribution }}.yaml"

      - name: Download zabbix repo package
        get_url:
            url: "{{ zabbix_repo_url }}"
            dest: /tmp/zabbix.deb

      - name: Install zabbix repo
        apt:
            deb: /tmp/zabbix.deb
            state: present

      - name: Install zabbix agent
        apt:
            name: zabbix-agent
            state: present
            update_cache: yes

      - name: Stop service zabbix-agent
        service:
            name: zabbix-agent
            state: stopped

      - name: Remove zabbix config file
        file:
            path: /etc/zabbix/zabbix_agentd.conf
            state: absent
            
      - name: download config
        get_url: "url={{zabbix_config_agent_url }} dest=/tmp/"

      - name: Create new zabbix config file from template
        template:
            src: "{{ ansible_all_ipv4_addresses }}/tmp/zabbix_agentd.conf.j2"
            dest: "/etc/zabbix/zabbix_agentd.conf"

      - name: Start service zabbix-agent
        service:
            name: zabbix-agent
            state: started
