---
- hosts: all
  gather_facts: true
  remote_user: root
  become: true
  ignore_errors: true

  tasks:
  - name:
    shell: /usr/bin/sshfs -o idmap=user,reconnect root@"{{ srv-ip}}":/data/sf-awx-bcp-user/bcp-linux /mnt/sshftps
