---
- hosts: all
  gather_facts: true
  become: true
  ignore_errors: true

  tasks:
  
  - name: add record to sftab
    lineinfile:
      path: "/etc/fstab"
      line: "#mount sftp"
      line: "192.168.168.13:/data/sf-awx-bcp-user/bcp-linux /mnt/sshftps/ fuse.sshfs defaults 0 0"
      
  - name: Mount DVD read-only
    mount:
      path: /mnt/sshftps/
      src: root@192.168.168.13:/data/sf-awx-bcp-user/bcp-linux /mnt/sshftps
      fstype: ext4
      state: present
    
  - name: mount sftp via shell *without reboot*
    raw: sudo mount -av

  #- name: create baremetal backup via dd to /nmt/sshftps
  #  shell: sudo dd if=/dev/sda conv=sync,noerror bs=64K | gzip -c  > /mnt/sshftps/{{ ansible_facts['nodename'] }}-{{ ansible_date_time.date }}.img.gz

  #- name: unmount sftp after backup
  #  shell: 'umount /mnt/sshftps'
